const tintColor = '#2f95dc';

export default {
    tintColor,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColor,
    tabBar: '#fefefe',
    errorBackground: 'red',
    errorText: '#fff',
    warningBackground: '#EAEB5E',
    warningText: '#666804',
    noticeBackground: tintColor,
    noticeText: '#fff',
    loginFirsGradient: '#32ccbc',
    loginSecondGradient: '#90f7ec',
    loginIconColor: '#32ccbc',
    loginInputBackground: '#fff',
    sendButtonCollor: '#a1eae3',
    sendIconCollor: '#d8d8d8',
    removeIconCollor: 'green',
    chatInputToolbarColor: '#333fff',
    failFirstGradient: '#32ccbc',
    failSecondGradient: '#f790e7',
    successFirstGradient: '#32ccbc',
    succesSecondGradient: '#90f7ec',
    pinCodeGradient: '#32ccbc',
    pinCodeButtonColor: '#FFFFFF',
    pinCodeCirculeButtonColor: '#ffffff',
    pinCodeCirculeButtonBackgroundColor: 'rgba(52, 52, 52, 0.0)',
};
